[package]
name = "fast-noise2-port"
version = "0.1.0"
edition = "2024"

[features]
default = ["std"]
std = []
libm = ["dep:libm"]

[dependencies]
libm = { version = "0.2.8", optional = true, default-features = false }
